Models/OwnerModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ClassicGarage.Models
{
    [Table("Owner")]
    public class OwnerModels
    {
        public int ID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public int PhoneNo { get; set; }
        [Required]
        public string Email { get; set; }

        public virtual ICollection<CarModels> Cars { get; set; }
    }
}

Controllers/OwnerModelsController.cs
using ClassicGarage.DAL;
using ClassicGarage.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClassicGarage.Controllers
{
    public class OwnerModelsController : Controller
    {
        private GarageContext db = new GarageContext();

        // GET: OwnerModel
        //[Authorize(Users = "admin@admin.pl")]
        [Authorize (Roles ="admin")]
        public ActionResult Index(int? id )
        {
          
            var viewModel = new GarageViewModels();

            viewModel.OwnerModels = db.Owners.Include(s => s.Cars);

            if (id != null)
            {
                ViewBag.Id_Owner = id.Value;
                viewModel.CarModels = db.Cars.Where(i => i.OwnerId == id.Value).Include(o => o.Advertisement).Include(m => m.Brand);
            }


            return View(viewModel);
        }

        // GET: OwnerModel
        //[Authorize(Users = "admin@admin.pl")]
        [Authorize(Roles = "user")]
        public ActionResult IndexUser()
        {
            var viewModel = new GarageViewModels();

            viewModel.OwnerModels = db.Owners.Where(i => i.Email==User.Identity.Name).Include(s => s.Cars);
            
            Console.WriteLine(viewModel.OwnerModels);

            return View(viewModel);
        }


        //nazwa taka sama jak nazwa pliku html
        [Authorize(Roles = "admin,user")]
        public ActionResult Details(int? id)
        {
            if(id==null)
            {
                return RedirectToAction("Index");
            }
            OwnerModels owner = db.Owners.Find(id);

            if(owner == null)
            {
                return HttpNotFound();
            }

            return View(owner);
        }

        [Authorize(Roles = "admin,user")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
           
            OwnerModels owner = db.Owners.Find(id);

            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,user")]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,PhoneNo,Email")] OwnerModels owner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(owner).State = EntityState.Modified;
                db.SaveChanges();
                if(User.IsInRole("admin"))
                {
                    return RedirectToAction("Index");
                } else
                {
                    return RedirectToAction("IndexUser");
                }
                
            }
            return View(owner);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerModels owner = db.Owners.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        // POST: /Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            OwnerModels owner = db.Owners.Find(id);
            db.Owners.Remove(owner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Create([Bind(Include ="FirstName, LastName, PhoneNo, Email")] OwnerModels owner)
        {
            if(ModelState.IsValid)
            {
                db.Owners.Add(owner);
                db.SaveChanges();
                if(User.IsInRole("admin"))
                {
                    return RedirectToAction("Index");
                } else
                {
                    return RedirectToAction("IndexUser");
                }
               
            }
            return View(owner);
        }
    }
}

Views/OwnerModels/Create.cshtml
@model ClassicGarage.Models.OwnerModels

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stwórz</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Właściciel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "Imię", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Nazwisko", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, "Nr. telefonu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.IsInRole("user"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @Value = User.Identity.Name, @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else if (User.IsInRole("admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        } else
        {
            <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @Value = User.Identity.Name, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            </div>
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (User.IsInRole("user"))
{
    <div>
        @Html.ActionLink("Wróć", "IndexUser")
    </div>
}
@if (User.IsInRole("admin"))
{
    <div>
        @Html.ActionLink("Wróć", "Index")
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/OwnerModels/Delete.cshtml
@model ClassicGarage.Models.OwnerModels

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuwanie</h2>

<h3>Jesteś pewny czy chcesz to usunąć?</h3>
<div>
    <h4>Właściciel</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Imię
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            Nazwisko
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            Nr. Telefonu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
            <br />
            @Html.ActionLink("Wróć", "Index")
        </div>
    }
</div>

Views/OwnerModels/Details.cshtml
@model ClassicGarage.Models.OwnerModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły</h2>


<dt>
    Imię
</dt>

<dd>
    @Html.DisplayFor(model => model.FirstName)
</dd>

<dt>
    Nazwisko
</dt>

<dd>
    @Html.DisplayFor(model => model.LastName)
</dd>

<dt>
    Nr. Telefonu
</dt>

<dd>
    @Html.DisplayFor(model => model.PhoneNo)
</dd>

<dt>
    @Html.DisplayNameFor(model => model.Email)
</dt>

<dd>
    @Html.DisplayFor(model => model.Email)
</dd>

@Html.ActionLink("Edytuj", "Edit", new { id = Model.ID })
<br />
<br />
@if (User.IsInRole("user"))
{
    @Html.ActionLink("Powrót", "IndexUser")
}
@if (User.IsInRole("admin"))
{
    @Html.ActionLink("Powrót", "Index")
}

Views/OwnerModels/Edit.cshtml
@model ClassicGarage.Models.OwnerModels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Właściciele</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "Imię", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Nazwisko", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, "Nr. telefonu", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        @*Genre and Price removed for brevity.*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@if (User.IsInRole("user"))
{
    @Html.ActionLink("Powrót", "IndexUser")
}
@if (User.IsInRole("admin"))
{
    @Html.ActionLink("Powrót", "Index")
}

Views/OwnerModels/Index.cshtml
@model ClassicGarage.Models.GarageViewModels

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Właściciele</h2>

<p>
    @Html.ActionLink("Stwórz nowy", "Create", "OwnerModels")
</p>

@{var headerMetadata = Model.OwnerModels.FirstOrDefault();}
<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Nazwisko
        </th>
        <th>
            Nr. Telefonu
        </th>
        <th>
            @Html.DisplayNameFor(model => headerMetadata.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.OwnerModels)
    {
        string selectedRow = "";
        if (item.ID == ViewBag.Id_Owner)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Pokaż detale", "Index", new { id = item.ID }) |
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Szczegóły", "Details", new { id = item.ID }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

@if (Model.CarModels != null)
{
    <h3>Samochody wybranego użytkownika</h3>
    var headerMetadataS = Model.CarModels.FirstOrDefault();

    <table class="table">
        <tr>
            <th>
                Właściciel
            </th>
            <th>
                Marka
            </th>
            <th>
                Model
            </th>
            <th>
                Rok
            </th>
            <th>
                Numer VIN
            </th>
            <th>
                Seria
            </th>
            <th>
                Zdjęcie
            </th>
            <th>
                Data zakupu
            </th>
            <th>
                Data sprzedaży
            </th>
            <th>
                Kwota zakupu
            </th>
            <th>
                Kwota sprzedaży
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.CarModels)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Owner.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VIN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Series)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Photo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SaleDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchasePrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SellPrice)
                </td>
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Szczegóły", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>

}

Views/OwnerModels/IndexUser.cshtml
@model ClassicGarage.Models.GarageViewModels

@{
    ViewBag.Title = "IndexUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profil Użytkownika</h2>

@{var headerMetadata = Model.OwnerModels.FirstOrDefault();}


<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Nazwisko
        </th>
        <th>
            Telefon
        </th>
        <th>
            @Html.DisplayNameFor(model => headerMetadata.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.OwnerModels)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Szczegóły", "Details", new { id = item.ID })
            </td>
        </tr>
    }

</table>